{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "theengs-gateway.namespace" . }}
  labels:
    {{- include "theengs-gateway.labels" . | nindent 4 }}
{{- end }}
