{{- if not .Values.mqtt.existingSecret }}
{{- if or .Values.mqtt.username .Values.mqtt.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theengs-gateway.secretName" . }}
  namespace: {{ include "theengs-gateway.namespace" . }}
  labels:
    {{- include "theengs-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.mqtt.username }}
  MQTT_USERNAME: {{ .Values.mqtt.username | quote }}
  {{- end }}
  {{- if .Values.mqtt.password }}
  MQTT_PASSWORD: {{ .Values.mqtt.password | quote }}
  {{- end }}
{{- end }}
{{- end }}
