apiVersion: v2
name: theengs-gateway
description: A Helm chart for deploying Theengs Gateway - a BLE to MQTT bridge
type: application
version: 0.1.4
appVersion: "v1.7.5.1"
keywords:
  - theengs
  - ble
  - mqtt
  - home-assistant
  - bluetooth
  - iot
home: https://theengs.io/
sources:
  - https://github.com/theengs/gateway
maintainers:
  - name: Your Name
    email: your-email@example.com
